HealthPlus/Controllers/EspecialidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HealthPlus.Service;
using HealthPlus.Models;

namespace HealthPlus.Controllers
{
    public class EspecialidadeController : Controller
    {
        public readonly EspecialidadeService especialidadeService = new EspecialidadeService();
        // GET: Especialidade
        public ActionResult Novo()
        {
            return View(new Especialidade());
        }

        [HttpPost]
        public ActionResult Novo(Especialidade e)
        {
            if (ModelState.IsValid)
            {
                especialidadeService.Add(e);
            }
            return View(e);
        }
    }
}

HealthPlus/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HealthPlus.Models;
using HealthPlus.Service;

namespace HealthPlus.Controllers
{
    public class HospitalController : Controller
    {
        //Instanciando o Service do Hospital
        protected readonly HospitalService hpService = new HospitalService();
        // GET: Hospital

        public ActionResult Index()
        {
         var v=   hpService.GetAll();
            return View(v);
        }
        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Novo(Hospital h)
        {
            if (ModelState.IsValid)
            {
                hpService.Add(h);
            }
            return View("Index");
        }
        
        
    }
}

HealthPlus/Controllers/MedicoController.cs
using HealthPlus.Context;
using HealthPlus.Models;
using HealthPlus.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HealthPlus.Controllers
{
    public class MedicoController : Controller

    {
        protected readonly EspecialidadeService especialidadeService = new EspecialidadeService();
        protected readonly MedicoService medicoService = new MedicoService();
        public readonly HealthPlusContexto Db = new HealthPlusContexto();


        // GET: Medico
        public ActionResult Index()
        {
            var m = medicoService.GetAll();
            return View(m);
        }

        public ActionResult Detalhes(int id)
        {
            return View();
        }
        public ActionResult Novo()
        {
            ViewBag.Especialidades = especialidadeService.GetAll().ToList();
            return View();
        }

        [HttpPost]
        //[ReponseType(typeof(Medico))]
        
        public ActionResult Novo([Bind(Include = "Id,Tipo")]Medico m,int[] espe)
        {
            //Recupero dados do Formulario
            var lstEsp = Request.Form["chkEsp"];
            if (!string.IsNullOrEmpty(lstEsp))
            {
                //Converto para inteiro e insiro em uma array
                espe = lstEsp.Split(',').Select(Int32.Parse).ToArray();
                
                if (espe.Count() >0)//Verifico se tem +0
                {
                    var PostsMedicos = medicoService.GetListaEspecialidade(espe).ToList();
                    //var PostMedicos = Db.Especialidades.Where(w => espe.Contains(w.Id)).ToList();
                    medicoService.AddRange(PostsMedicos);
                    
                    //var PostMedico = especialidadeService.GetListaEspecialidade(splEsp);
                    //especialidadeService.AddRange(PostMedico);
                }
            }

            if (ModelState.IsValid)
            {


                Db.Medicos.Add(m);
                Db.SaveChanges();
                //medicoService.Add(m);

                return RedirectToAction("Index");
            }
            return View(m);
        }

       
        public ActionResult Editar(int id)
        {
           Medico medico= medicoService.GetById(id);


            return View(medico);
        }
        [HttpPost]
        public ActionResult Editar(Medico medico)
        {

            medicoService.Update(medico);
            return RedirectToAction("Index");
        }

 

        
    

    }
}

HealthPlus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Health Plus</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Health Plus", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <!--Verificar se está logado, se estiver exibir Menu-->
                    @if (true)
                    {
                        <li>@Html.ActionLink("Médicos", "Index", "Medico")</li>
                        <li>@Html.ActionLink("Hospitais", "Index", "Hospital")</li>
                        <li>@Html.ActionLink("Especialidades","Novo", "Especialidade")</li>
                        <li>@Html.ActionLink("Agenda", "Index", "Agenda")</li>
                    }
                </ul>

                <div align="right">
                    <!--Se Logado exibir Logoff-->
                    <!-- @if (!true)
                      {
                      <a href="/" class="btn btn-default" style="margin-top:8px;">Login</a>
                      }
                      else
                      {
                      <a href="/" class="btn btn-default" style="margin-top:8px;">Logoff</a>
                      }-->
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Health Plus</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", false)
</body>
</html>